/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: bboucher <bboucher@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/02/22 16:53:03 by bboucher          #+#    #+#             */
/*   Updated: 2019/02/22 18:39:33 by bboucher         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_printf.h"

int main()
{
	char	*str;
	str = "Testing";

	printf("===|%s$\n", str);
	ft_printf(">>>|%s$\n", str);	
	printf("\n");
	printf("===|%c$\n", 'c');
	ft_printf(">>>|%c$\n", 'c');
	printf("\n");
	printf("===|%.0s$\n", str);
	ft_printf(">>>|%.0s$\n", str);
	printf("\n");
	printf("===|%.5s$\n", str);
	ft_printf(">>>|%.5s$\n", str);
	printf("\n");
	printf("===|%.15s$\n", str);
	ft_printf(">>>|%.15s$\n", str);
	printf("\n");
	printf("===|%-.5s$\n", str);
	ft_printf(">>>|%-.5s$\n", str);
	printf("\n");
	printf("===|%5s$\n", str);
	ft_printf(">>>|%5s$\n", str);
	printf("\n");
	printf("===|%15s$\n", str);
	ft_printf(">>>|%15s$\n", str);
	printf("\n");
	printf("===|%-5s$\n", str);
	ft_printf(">>>|%-5s$\n", str);
	printf("\n");
	printf("===|%-15s$\n", str);
	ft_printf(">>>|%-15s$\n", str);
	printf("\n");
	printf("===|%-15.5s$\n", str);
	ft_printf(">>>|%-15.5s$\n", str);
	printf("\n");
	printf("===|%12s$\n", NULL);
	ft_printf(">>>|%12s$\n", NULL);
	printf("\n");
	printf("===|%1s$\n", NULL);
	ft_printf(">>>|%1s$\n", NULL);
	printf("\n");
	printf("===|%-5.6s$\n", NULL);
	ft_printf(">>>|%-5.6s$\n", NULL);
	printf("\n");
	printf("===|%-.8s$\n", NULL);
	ft_printf(">>>|%-.8s$\n", NULL);
	printf("\n");
	printf("===|%.12s$\n", NULL);
	ft_printf(">>>|%.12s$\n", NULL);
	printf("\n");
	printf("===|%-.5s$\n", "");
	ft_printf(">>>|%-.5s$\n", "");
	printf("\n");
	printf("===|%-1.32s$\n", "");
	ft_printf(">>>|%-1.32s$\n", "");
	printf("\n");
	printf("===|%1.4s$\n", "");
	ft_printf(">>>|%1.4s$\n", "");
	printf("\n");
	printf("===|%23s$\n", "");
	ft_printf(">>>|%23s$\n", "");
	printf("\n");

	str = "abcdefghijklmnop";

	printf("===|%s$\n", str);
	ft_printf(">>>|%s$\n", str);
	printf("\n");
	printf("===|%.0s$\n", str);
	ft_printf(">>>|%.0s$\n", str);
	printf("\n");
	printf("===|%.5s$\n", str);
	ft_printf(">>>|%.5s$\n", str);
	printf("\n");
	printf("===|%.15s$\n", str);
	ft_printf(">>>|%.15s$\n", str);
	printf("\n");
	printf("===|%-.5s$\n", str);
	ft_printf(">>>|%-.5s$\n", str);
	printf("\n");
	printf("===|%5s$\n", str);
	ft_printf(">>>|%5s$\n", str);
	printf("\n");
	printf("===|%15s$\n", str);
	ft_printf(">>>|%15s$\n", str);
	printf("\n");
	printf("===|%-5s$\n", str);
	ft_printf(">>>|%-5s$\n", str);
	printf("\n");
	printf("===|%-15s$\n", str);
	ft_printf(">>>|%-15s$\n", str);
	printf("\n");
	printf("===|%-15.5s$\n", str);
	ft_printf(">>>|%-15.5s$\n", str);
	printf("\n");
	printf("===|%12s$\n", NULL);
	ft_printf(">>>|%12s$\n", NULL);
	printf("\n");
	printf("===|%1s$\n", NULL);
	ft_printf(">>>|%1s$\n", NULL);
	printf("\n");
	printf("===|%-5.6s$\n", NULL);
	ft_printf(">>>|%-5.6s$\n", NULL);
	printf("\n");
	printf("===|%-.8s$\n", NULL);
	ft_printf(">>>|%-.8s$\n", NULL);
	printf("\n");
	printf("===|%.12s$\n", NULL);
	ft_printf(">>>|%.12s$\n", NULL);
	printf("\n");
	printf("===|%-.5s$\n", "");
	ft_printf(">>>|%-.5s$\n", "");
	printf("\n");
	printf("===|%-1.32s$\n", "");
	ft_printf(">>>|%-1.32s$\n", "");
	printf("\n");
	printf("===|%1.4s$\n", "");
	ft_printf(">>>|%1.4s$\n", "");
	printf("\n");
	printf("===|%23s$\n", "");
	ft_printf(">>>|%23s$\n", "");
	printf("\n");

	str = "ASD ASDqw ldmj23oi4j32o u89usadjjals j238ujh4 2ojasd  ijo238e 9juasido 8123ue aklnsdk jalhdls$\n";

	printf("===|%s$\n", str);
	ft_printf(">>>|%s$\n", str);
	printf("\n");
	printf("===|%.0s$\n", str);
	ft_printf(">>>|%.0s$\n", str);
	printf("\n");
	printf("===|%.5s$\n", str);
	ft_printf(">>>|%.5s$\n", str);
	printf("\n");
	printf("===|%.15s$\n", str);
	ft_printf(">>>|%.15s$\n", str);
	printf("\n");
	printf("===|%-.5s$\n", str);
	ft_printf(">>>|%-.5s$\n", str);
	printf("\n");
	printf("===|%5s$\n", str);
	ft_printf(">>>|%5s$\n", str);
	printf("\n");
	printf("===|%15s$\n", str);
	ft_printf(">>>|%15s$\n", str);
	printf("\n");
	printf("===|%-5s$\n", str);
	ft_printf(">>>|%-5s$\n", str);
	printf("\n");
	printf("===|%-15s$\n", str);
	ft_printf(">>>|%-15s$\n", str);
	printf("\n");
	printf("===|%-15.5s$\n", str);
	ft_printf(">>>|%-15.5s$\n", str);
	printf("\n");
	printf("===|%12s$\n", NULL);
	ft_printf(">>>|%12s$\n", NULL);
	printf("\n");
	printf("===|%1s$\n", NULL);
	ft_printf(">>>|%1s$\n", NULL);
	printf("\n");
	printf("===|%-5.6s$\n", NULL);
	ft_printf(">>>|%-5.6s$\n", NULL);
	printf("\n");
	printf("===|%-.8s$\n", NULL);
	ft_printf(">>>|%-.8s$\n", NULL);
	printf("\n");
	printf("===|%.12s$\n", NULL);
	ft_printf(">>>|%.12s$\n", NULL);
	printf("\n");
	printf("===|%-.5s$\n", "");
	ft_printf(">>>|%-.5s$\n", "");
	printf("\n");
	printf("===|%-1.32s$\n", "");
	ft_printf(">>>|%-1.32s$\n", "");
	printf("\n");
	printf("===|%1.4s$\n", "");
	ft_printf(">>>|%1.4s$\n", "");
	printf("\n");
	printf("===|%23s$\n", "");
	ft_printf(">>>|%23s$\n", "");
	printf("\n");

	str = "";

	printf("===|%s$\n", str);
	ft_printf(">>>|%s$\n", str);
	printf("\n");
	printf("===|%.0s$\n", str);
	ft_printf(">>>|%.0s$\n", str);
	printf("\n");
	printf("===|%.5s$\n", str);
	ft_printf(">>>|%.5s$\n", str);
	printf("\n");
	printf("===|%.15s$\n", str);
	ft_printf(">>>|%.15s$\n", str);
	printf("\n");
	printf("===|%-.5s$\n", str);
	ft_printf(">>>|%-.5s$\n", str);
	printf("\n");
	printf("===|%5s$\n", str);
	ft_printf(">>>|%5s$\n", str);
	printf("\n");
	printf("===|%15s$\n", str);
	ft_printf(">>>|%15s$\n", str);
	printf("\n");
	printf("===|%-5s$\n", str);
	ft_printf(">>>|%-5s$\n", str);
	printf("\n");
	printf("===|%-15s$\n", str);
	ft_printf(">>>|%-15s$\n", str);
	printf("\n");
	printf("===|%-15.5s$\n", str);
	ft_printf(">>>|%-15.5s$\n", str);
	printf("\n");
	printf("===|%12s$\n", NULL);
	ft_printf(">>>|%12s$\n", NULL);
	printf("\n");
	printf("===|%1s$\n", NULL);
	ft_printf(">>>|%1s$\n", NULL);
	printf("\n");
	printf("===|%-5.6s$\n", NULL);
	ft_printf(">>>|%-5.6s$\n", NULL);
	printf("\n");
	printf("===|%-.8s$\n", NULL);
	ft_printf(">>>|%-.8s$\n", NULL);
	printf("\n");
	printf("===|%.12s$\n", NULL);
	ft_printf(">>>|%.12s$\n", NULL);
	printf("\n");
	printf("===|%-.5s$\n", "");
	ft_printf(">>>|%-.5s$\n", "");
	printf("\n");
	printf("===|%-1.32s$\n", "");
	ft_printf(">>>|%-1.32s$\n", "");
	printf("\n");
	printf("===|%1.4s$\n", "");
	ft_printf(">>>|%1.4s$\n", "");
	printf("\n");
	printf("===|%23s$\n", "");
	ft_printf(">>>|%23s$\n", "");
	printf("\n");

	str = "NULL";

	printf("===|%s$\n", str);
	ft_printf(">>>|%s$\n", str);
	printf("\n");
	printf("===|%.0s$\n", str);
	ft_printf(">>>|%.0s$\n", str);
	printf("\n");
	printf("===|%.5s$\n", str);
	ft_printf(">>>|%.5s$\n", str);
	printf("\n");
	printf("===|%.15s$\n", str);
	ft_printf(">>>|%.15s$\n", str);
	printf("\n");
	printf("===|%-.5s$\n", str);
	ft_printf(">>>|%-.5s$\n", str);
	printf("\n");
	printf("===|%5s$\n", str);
	ft_printf(">>>|%5s$\n", str);
	printf("\n");
	printf("===|%15s$\n", str);
	ft_printf(">>>|%15s$\n", str);
	printf("\n");
	printf("===|%-5s$\n", str);
	ft_printf(">>>|%-5s$\n", str);
	printf("\n");
	printf("===|%-15s$\n", str);
	ft_printf(">>>|%-15s$\n", str);
	printf("\n");
	printf("===|%-15.5s$\n", str);
	ft_printf(">>>|%-15.5s$\n", str);
	printf("\n");
	printf("===|%12s$\n", NULL);
	ft_printf(">>>|%12s$\n", NULL);
	printf("\n");
	printf("===|%1s$\n", NULL);
	ft_printf(">>>|%1s$\n", NULL);
	printf("\n");
	printf("===|%-5.6s$\n", NULL);
	ft_printf(">>>|%-5.6s$\n", NULL);
	printf("\n");
	printf("===|%-.8s$\n", NULL);
	ft_printf(">>>|%-.8s$\n", NULL);
	printf("\n");
	printf("===|%.12s$\n", NULL);
	ft_printf(">>>|%.12s$\n", NULL);
	printf("\n");
	printf("===|%-.5s$\n", "");
	ft_printf(">>>|%-.5s$\n", "");
	printf("\n");
	printf("===|%-1.32s$\n", "");
	ft_printf(">>>|%-1.32s$\n", "");
	printf("\n");
	printf("===|%1.4s$\n", "");
	ft_printf(">>>|%1.4s$\n", "");
	printf("\n");
	printf("===|%23s$\n", "");
	ft_printf(">>>|%23s$\n", "");
	printf("\n");

	while (1);
	return (0);
}
