/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: bboucher <bboucher@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/01/31 14:00:10 by bclaudio          #+#    #+#             */
/*   Updated: 2019/02/25 10:38:29 by bboucher         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_printf.h"
#include <limits.h>


int main()
{
	int nb1 = -45;
	printf("===|% d$\n", nb1);
	ft_printf(">>>|% d$\n", nb1);
	printf("\n");
	printf("===|%+d$\n", nb1);
	ft_printf(">>>|%+d$\n", nb1);
	printf("\n");
	printf("===|%.5d$\n", nb1);
	ft_printf(">>>|%.5d$\n", nb1);
	printf("\n");
	printf("===|% .5d$\n", nb1);
	ft_printf(">>>|% .5d$\n", nb1);
	printf("\n");
	printf("===|%+.5d$\n", nb1);
	ft_printf(">>>|%+.5d$\n", nb1);
	printf("\n");
	printf("===|%+.0d$\n", nb1);
	ft_printf(">>>|%+.0d$\n", nb1);
	printf("\n");
	printf("===|%0.5d$\n", nb1);
	ft_printf(">>>|%0.5d$\n", nb1);
	printf("\n");
	printf("===|%-.5d$\n", nb1);
	ft_printf(">>>|%-.5d$\n", nb1);
	printf("\n");
	printf("===|%5d$\n", nb1);
	ft_printf(">>>|%5d$\n", nb1);
	printf("\n");
	printf("===|% 5d$\n", nb1);
	ft_printf(">>>|% 5d$\n", nb1);
	printf("\n");
	printf("===|%+5d$\n", nb1);
	ft_printf(">>>|%+5d$\n", nb1);
	printf("\n");
	printf("===|%-5d$\n", nb1);
	ft_printf(">>>|%-5d$\n", nb1);
	printf("\n");
	printf("===|%05d$\n", nb1);
	ft_printf(">>>|%05d$\n", nb1);
	printf("\n");
	printf("===|%+05d$\n", nb1);
	ft_printf(">>>|%+05d$\n", nb1);
	printf("\n");
	printf("===|%0+5d$\n", nb1);
	ft_printf(">>>|%0+5d$\n", nb1);
	printf("\n");
	printf("===|%05.3d$\n", nb1);
	ft_printf(">>>|%05.3d$\n", nb1);
	printf("\n");
	printf("===|%-5.3d$\n", nb1);
	ft_printf(">>>|%-5.3d$\n", nb1);
	printf("\n");
	printf("===|%+05.3d$\n", nb1);
	ft_printf(">>>|%+05.3d$\n", nb1);
	printf("\n");
	printf("===|%0 5.3d$\n", nb1);
	ft_printf(">>>|%0 5.3d$\n", nb1);
	printf("\n");
	printf("===|% 05.3d$\n", nb1);
	ft_printf(">>>|% 05.3d$\n", nb1);
	printf("\n");
	printf("===|%-+5.3d$\n", nb1);
	ft_printf(">>>|%-+5.3d$\n", nb1);
	printf("\n");
	printf("===|% i$\n", nb1);
	ft_printf(">>>|% i$\n", nb1);
	printf("\n");
	printf("===|%+i$\n", nb1);
	ft_printf(">>>|%+i$\n", nb1);
	printf("\n");
	printf("===|%.5i$\n", nb1);
	ft_printf(">>>|%.5i$\n", nb1);
	printf("\n");
	printf("===|% .5i$\n", nb1);
	ft_printf(">>>|% .5i$\n", nb1);
	printf("\n");
	printf("===|%+.5i$\n", nb1);
	ft_printf(">>>|%+.5i$\n", nb1);
	printf("\n");
	printf("===|%+.0i$\n", nb1);
	ft_printf(">>>|%+.0i$\n", nb1);
	printf("\n");
	printf("===|%0.5i$\n", nb1);
	ft_printf(">>>|%0.5i$\n", nb1);
	printf("\n");
	printf("===|%-.5i$\n", nb1);
	ft_printf(">>>|%-.5i$\n", nb1);
	printf("\n");
	printf("===|%5i$\n", nb1);
	ft_printf(">>>|%5i$\n", nb1);
	printf("\n");
	printf("===|% 5i$\n", nb1);
	ft_printf(">>>|% 5i$\n", nb1);
	printf("\n");
	printf("===|%+5i$\n", nb1);
	ft_printf(">>>|%+5i$\n", nb1);
	printf("\n");
	printf("===|%-5i$\n", nb1);
	ft_printf(">>>|%-5i$\n", nb1);
	printf("\n");
	printf("===|%05i$\n", nb1);
	ft_printf(">>>|%05i$\n", nb1);
	printf("\n");
	printf("===|%+05i$\n", nb1);
	ft_printf(">>>|%+05i$\n", nb1);
	printf("\n");
	printf("===|%0+5i$\n", nb1);
	ft_printf(">>>|%0+5i$\n", nb1);
	printf("\n");
	printf("===|%05.3i$\n", nb1);
	ft_printf(">>>|%05.3i$\n", nb1);
	printf("\n");
	printf("===|%-5.3i$\n", nb1);
	ft_printf(">>>|%-5.3i$\n", nb1);
	printf("\n");
	printf("===|%+05.3i$\n", nb1);
	ft_printf(">>>|%+05.3i$\n", nb1);
	printf("\n");
	printf("===|%0 5.3i$\n", nb1);
	ft_printf(">>>|%0 5.3i$\n", nb1);
	printf("\n");
	printf("===|% 05.3i$\n", nb1);
	ft_printf(">>>|% 05.3i$\n", nb1);
	printf("\n");
	printf("===|%-+5.3i$\n", nb1);
	ft_printf(">>>|%-+5.3i$\n", nb1);
	printf("\n");

	int nb2 = 0;
	printf("===|% d$\n", nb2);
	ft_printf(">>>|% d$\n", nb2);
	printf("\n");
	printf("===|%+d$\n", nb2);
	ft_printf(">>>|%+d$\n", nb2);
	printf("\n");
	printf("===|%.5d$\n", nb2);
	ft_printf(">>>|%.5d$\n", nb2);
	printf("\n");
	printf("===|% .5d$\n", nb2);
	ft_printf(">>>|% .5d$\n", nb2);
	printf("\n");
	printf("===|%+.5d$\n", nb2);
	ft_printf(">>>|%+.5d$\n", nb2);
	printf("\n");
	printf("===|%0.5d$\n", nb2);
	ft_printf(">>>|%0.5d$\n", nb2);
	printf("\n");
	printf("===|%-.5d$\n", nb2);
	ft_printf(">>>|%-.5d$\n", nb2);
	printf("\n");
	printf("===|%5d$\n", nb2);
	ft_printf(">>>|%5d$\n", nb2);
	printf("\n");
	printf("===|% 5d$\n", nb2);
	ft_printf(">>>|% 5d$\n", nb2);
	printf("\n");
	printf("===|%+5d$\n", nb2);
	ft_printf(">>>|%+5d$\n", nb2);
	printf("\n");
	printf("===|%-5d$\n", nb2);
	ft_printf(">>>|%-5d$\n", nb2);
	printf("\n");
	printf("===|%05d$\n", nb2);
	ft_printf(">>>|%05d$\n", nb2);
	printf("\n");
	printf("===|%+05d$\n", nb2);
	ft_printf(">>>|%+05d$\n", nb2);
	printf("\n");
	printf("===|%0+5d$\n", nb2);
	ft_printf(">>>|%0+5d$\n", nb2);
	printf("\n");
	printf("===|%05.3d$\n", nb2);
	ft_printf(">>>|%05.3d$\n", nb2);
	printf("\n");
	printf("===|%-5.3d$\n", nb2);
	ft_printf(">>>|%-5.3d$\n", nb2);
	printf("\n");
	printf("===|%+05.3d$\n", nb2);
	ft_printf(">>>|%+05.3d$\n", nb2);
	printf("\n");
	printf("===|%0 5.3d$\n", nb2);
	ft_printf(">>>|%0 5.3d$\n", nb2);
	printf("\n");
	printf("===|% 05.3d$\n", nb2);
	ft_printf(">>>|% 05.3d$\n", nb2);
	printf("\n");
	printf("===|%-+5.3d$\n", nb2);
	ft_printf(">>>|%-+5.3d$\n", nb2);
	printf("\n");

	int nb3 = -879650;
	printf("===|% d$\n", nb3);
	ft_printf(">>>|% d$\n", nb3);
	printf("\n");
	printf("===|%+d$\n", nb3);
	ft_printf(">>>|%+d$\n", nb3);
	printf("\n");
	printf("===|%.5d$\n", nb3);
	ft_printf(">>>|%.5d$\n", nb3);
	printf("\n");
	printf("===|% .5d$\n", nb3);
	ft_printf(">>>|% .5d$\n", nb3);
	printf("\n");
	printf("===|%+.5d$\n", nb3);
	ft_printf(">>>|%+.5d$\n", nb3);
	printf("\n");
	printf("===|%0.5d$\n", nb3);
	ft_printf(">>>|%0.5d$\n", nb3);
	printf("\n");
	printf("===|%-.5d$\n", nb3);
	ft_printf(">>>|%-.5d$\n", nb3);
	printf("\n");
	printf("===|%5d$\n", nb3);
	ft_printf(">>>|%5d$\n", nb3);
	printf("\n");
	printf("===|% 5d$\n", nb3);
	ft_printf(">>>|% 5d$\n", nb3);
	printf("\n");
	printf("===|%+5d$\n", nb3);
	ft_printf(">>>|%+5d$\n", nb3);
	printf("\n");
	printf("===|%-5d$\n", nb3);
	ft_printf(">>>|%-5d$\n", nb3);
	printf("\n");
	printf("===|%05d$\n", nb3);
	ft_printf(">>>|%05d$\n", nb3);
	printf("\n");
	printf("===|%+05d$\n", nb3);
	ft_printf(">>>|%+05d$\n", nb3);
	printf("\n");
	printf("===|%0+5d$\n", nb3);
	ft_printf(">>>|%0+5d$\n", nb3);
	printf("\n");
	printf("===|%05.3d$\n", nb3);
	ft_printf(">>>|%05.3d$\n", nb3);
	printf("\n");
	printf("===|%-5.3d$\n", nb3);
	ft_printf(">>>|%-5.3d$\n", nb3);
	printf("\n");
	printf("===|%+05.3d$\n", nb3);
	ft_printf(">>>|%+05.3d$\n", nb3);
	printf("\n");
	printf("===|%0 5.3d$\n", nb3);
	ft_printf(">>>|%0 5.3d$\n", nb3);
	printf("\n");
	printf("===|% 05.3d$\n", nb3);
	ft_printf(">>>|% 05.3d$\n", nb3);
	printf("\n");
	printf("===|%-+5.3d$\n", nb3);
	ft_printf(">>>|%-+5.3d$\n", nb3);
	printf("\n");

	int nb4 = -9856;
	printf("===|% d$\n", nb4);
	ft_printf(">>>|% d$\n", nb4);
	printf("\n");
	printf("===|%+d$\n", nb4);
	ft_printf(">>>|%+d$\n", nb4);
	printf("\n");
	printf("===|%.5d$\n", nb4);
	ft_printf(">>>|%.5d$\n", nb4);
	printf("\n");
	printf("===|% .5d$\n", nb4);
	ft_printf(">>>|% .5d$\n", nb4);
	printf("\n");
	printf("===|%+.5d$\n", nb4);
	ft_printf(">>>|%+.5d$\n", nb4);
	printf("\n");
	printf("===|%0.5d$\n", nb4);
	ft_printf(">>>|%0.5d$\n", nb4);
	printf("\n");
	printf("===|%-.5d$\n", nb4);
	ft_printf(">>>|%-.5d$\n", nb4);
	printf("\n");
	printf("===|%5d$\n", nb4);
	ft_printf(">>>|%5d$\n", nb4);
	printf("\n");
	printf("===|% 5d$\n", nb4);
	ft_printf(">>>|% 5d$\n", nb4);
	printf("\n");
	printf("===|%+5d$\n", nb4);
	ft_printf(">>>|%+5d$\n", nb4);
	printf("\n");
	printf("===|%-5d$\n", nb4);
	ft_printf(">>>|%-5d$\n", nb4);
	printf("\n");
	printf("===|%05d$\n", nb4);
	ft_printf(">>>|%05d$\n", nb4);
	printf("\n");
	printf("===|%+05d$\n", nb4);
	ft_printf(">>>|%+05d$\n", nb4);
	printf("\n");
	printf("===|%0+5d$\n", nb4);
	ft_printf(">>>|%0+5d$\n", nb4);
	printf("\n");
	printf("===|%05.3d$\n", nb4);
	ft_printf(">>>|%05.3d$\n", nb4);
	printf("\n");
	printf("===|%-5.3d$\n", nb4);
	ft_printf(">>>|%-5.3d$\n", nb4);
	printf("\n");
	printf("===|%+05.3d$\n", nb4);
	ft_printf(">>>|%+05.3d$\n", nb4);
	printf("\n");
	printf("===|%0 5.3d$\n", nb4);
	ft_printf(">>>|%0 5.3d$\n", nb4);
	printf("\n");
	printf("===|% 05.3d$\n", nb4);
	ft_printf(">>>|% 05.3d$\n", nb4);
	printf("\n");
	printf("===|%-+5.3d$\n", nb4);
	ft_printf(">>>|%-+5.3d$\n", nb4);
	printf("\n");

	int nb5 = 56432;
	printf("===|% d$\n", nb5);
	ft_printf(">>>|% d$\n", nb5);
	printf("\n");
	printf("===|%+d$\n", nb5);
	ft_printf(">>>|%+d$\n", nb5);
	printf("\n");
	printf("===|%.5d$\n", nb5);
	ft_printf(">>>|%.5d$\n", nb5);
	printf("\n");
	printf("===|% .5d$\n", nb5);
	ft_printf(">>>|% .5d$\n", nb5);
	printf("\n");
	printf("===|%+.5d$\n", nb5);
	ft_printf(">>>|%+.5d$\n", nb5);
	printf("\n");
	printf("===|%0.5d$\n", nb5);
	ft_printf(">>>|%0.5d$\n", nb5);
	printf("\n");
	printf("===|%-.5d$\n", nb5);
	ft_printf(">>>|%-.5d$\n", nb5);
	printf("\n");
	printf("===|%5d$\n", nb5);
	ft_printf(">>>|%5d$\n", nb5);
	printf("\n");
	printf("===|% 5d$\n", nb5);
	ft_printf(">>>|% 5d$\n", nb5);
	printf("\n");
	printf("===|%+5d$\n", nb5);
	ft_printf(">>>|%+5d$\n", nb5);
	printf("\n");
	printf("===|%-5d$\n", nb5);
	ft_printf(">>>|%-5d$\n", nb5);
	printf("\n");
	printf("===|%05d$\n", nb5);
	ft_printf(">>>|%05d$\n", nb5);
	printf("\n");
	printf("===|%+05d$\n", nb5);
	ft_printf(">>>|%+05d$\n", nb5);
	printf("\n");
	printf("===|%0+5d$\n", nb5);
	ft_printf(">>>|%0+5d$\n", nb5);
	printf("\n");
	printf("===|%05.3d$\n", nb5);
	ft_printf(">>>|%05.3d$\n", nb5);
	printf("\n");
	printf("===|%-5.3d$\n", nb5);
	ft_printf(">>>|%-5.3d$\n", nb5);
	printf("\n");
	printf("===|%+05.3d$\n", nb5);
	ft_printf(">>>|%+05.3d$\n", nb5);
	printf("\n");
	printf("===|%0 5.3d$\n", nb5);
	ft_printf(">>>|%0 5.3d$\n", nb5);
	printf("\n");
	printf("===|% 05.3d$\n", nb5);
	ft_printf(">>>|% 05.3d$\n", nb5);
	printf("\n");
	printf("===|%-+5.3d$\n", nb5);
	ft_printf(">>>|%-+5.3d$\n", nb5);
	printf("\n");

	long nb6 = 5643256546946846;
	printf("===|% ld$\n", nb6);
	ft_printf(">>>|% ld$\n", nb6);
	printf("\n");
	printf("===|%+ld$\n", nb6);
	ft_printf(">>>|%+ld$\n", nb6);
	printf("\n");
	printf("===|%.5ld$\n", nb6);
	ft_printf(">>>|%.5ld$\n", nb6);
	printf("\n");
	printf("===|% .5ld$\n", nb6);
	ft_printf(">>>|% .5ld$\n", nb6);
	printf("\n");
	printf("===|%+.5ld$\n", nb6);
	ft_printf(">>>|%+.5ld$\n", nb6);
	printf("\n");
	printf("===|%0.5ld$\n", nb6);
	ft_printf(">>>|%0.5ld$\n", nb6);
	printf("\n");
	printf("===|%-.5ld$\n", nb6);
	ft_printf(">>>|%-.5ld$\n", nb6);
	printf("\n");
	printf("===|%5ld$\n", nb6);
	ft_printf(">>>|%5ld$\n", nb6);
	printf("\n");
	printf("===|% 5ld$\n", nb6);
	ft_printf(">>>|% 5ld$\n", nb6);
	printf("\n");
	printf("===|%+5ld$\n", nb6);
	ft_printf(">>>|%+5ld$\n", nb6);
	printf("\n");
	printf("===|%-5ld$\n", nb6);
	ft_printf(">>>|%-5ld$\n", nb6);
	printf("\n");
	printf("===|%05ld$\n", nb6);
	ft_printf(">>>|%05ld$\n", nb6);
	printf("\n");
	printf("===|%+05ld$\n", nb6);
	ft_printf(">>>|%+05ld$\n", nb6);
	printf("\n");
	printf("===|%0+5ld$\n", nb6);
	ft_printf(">>>|%0+5ld$\n", nb6);
	printf("\n");
	printf("===|%05.3ld$\n", nb6);
	ft_printf(">>>|%05.3ld$\n", nb6);
	printf("\n");
	printf("===|%-5.3ld$\n", nb6);
	ft_printf(">>>|%-5.3ld$\n", nb6);
	printf("\n");
	printf("===|%+05.3ld$\n", nb6);
	ft_printf(">>>|%+05.3ld$\n", nb6);
	printf("\n");
	printf("===|%0 5.3ld$\n", nb6);
	ft_printf(">>>|%0 5.3ld$\n", nb6);
	printf("\n");
	printf("===|% 05.3ld$\n", nb6);
	ft_printf(">>>|% 05.3ld$\n", nb6);
	printf("\n");
	printf("===|%-+5.3ld$\n", nb6);
	ft_printf(">>>|%-+5.3ld$\n", nb6);
	printf("\n");

	long long nb7 = 5643254623165146555;
	printf("===|% lld$\n", nb7);
	ft_printf(">>>|% lld$\n", nb7);
	printf("\n");
	printf("===|%+lld$\n", nb7);
	ft_printf(">>>|%+lld$\n", nb7);
	printf("\n");
	printf("===|%.5lld$\n", nb7);
	ft_printf(">>>|%.5lld$\n", nb7);
	printf("\n");
	printf("===|% .5lld$\n", nb7);
	ft_printf(">>>|% .5lld$\n", nb7);
	printf("\n");
	printf("===|%+.5lld$\n", nb7);
	ft_printf(">>>|%+.5lld$\n", nb7);
	printf("\n");
	printf("===|%0.5lld$\n", nb7);
	ft_printf(">>>|%0.5lld$\n", nb7);
	printf("\n");
	printf("===|%-.5lld$\n", nb7);
	ft_printf(">>>|%-.5lld$\n", nb7);
	printf("\n");
	printf("===|%5lld$\n", nb7);
	ft_printf(">>>|%5lld$\n", nb7);
	printf("\n");
	printf("===|% 5lld$\n", nb7);
	ft_printf(">>>|% 5lld$\n", nb7);
	printf("\n");
	printf("===|%+5lld$\n", nb7);
	ft_printf(">>>|%+5lld$\n", nb7);
	printf("\n");
	printf("===|%-5lld$\n", nb7);
	ft_printf(">>>|%-5lld$\n", nb7);
	printf("\n");
	printf("===|%05lld$\n", nb7);
	ft_printf(">>>|%05lld$\n", nb7);
	printf("\n");
	printf("===|%+05lld$\n", nb7);
	ft_printf(">>>|%+05lld$\n", nb7);
	printf("\n");
	printf("===|%0+5lld$\n", nb7);
	ft_printf(">>>|%0+5lld$\n", nb7);
	printf("\n");
	printf("===|%05.3lld$\n", nb7);
	ft_printf(">>>|%05.3lld$\n", nb7);
	printf("\n");
	printf("===|%-5.3lld$\n", nb7);
	ft_printf(">>>|%-5.3lld$\n", nb7);
	printf("\n");
	printf("===|%+05.3lld$\n", nb7);
	ft_printf(">>>|%+05.3lld$\n", nb7);
	printf("\n");
	printf("===|%0 5.3lld$\n", nb7);
	ft_printf(">>>|%0 5.3lld$\n", nb7);
	printf("\n");
	printf("===|% 05.3lld$\n", nb7);
	ft_printf(">>>|% 05.3lld$\n", nb7);
	printf("\n");
	printf("===|%-+5.3lld$\n", nb7);
	ft_printf(">>>|%-+5.3lld$\n", nb7);
	printf("\n");

	char nb8 = 125;
	printf("===|% hhd$\n", nb8);
	ft_printf(">>>|% hhd$\n", nb8);
	printf("\n");
	printf("===|%+hhd$\n", nb8);
	ft_printf(">>>|%+hhd$\n", nb8);
	printf("\n");
	printf("===|%.5hhd$\n", nb8);
	ft_printf(">>>|%.5hhd$\n", nb8);
	printf("\n");
	printf("===|% .5hhd$\n", nb8);
	ft_printf(">>>|% .5hhd$\n", nb8);
	printf("\n");
	printf("===|%+.5hhd$\n", nb8);
	ft_printf(">>>|%+.5hhd$\n", nb8);
	printf("\n");
	printf("===|%0.5hhd$\n", nb8);
	ft_printf(">>>|%0.5hhd$\n", nb8);
	printf("\n");
	printf("===|%-.5hhd$\n", nb8);
	ft_printf(">>>|%-.5hhd$\n", nb8);
	printf("\n");
	printf("===|%5hhd$\n", nb8);
	ft_printf(">>>|%5hhd$\n", nb8);
	printf("\n");
	printf("===|% 5hhd$\n", nb8);
	ft_printf(">>>|% 5hhd$\n", nb8);
	printf("\n");
	printf("===|%+5hhd$\n", nb8);
	ft_printf(">>>|%+5hhd$\n", nb8);
	printf("\n");
	printf("===|%-5hhd$\n", nb8);
	ft_printf(">>>|%-5hhd$\n", nb8);
	printf("\n");
	printf("===|%05hhd$\n", nb8);
	ft_printf(">>>|%05hhd$\n", nb8);
	printf("\n");
	printf("===|%+05hhd$\n", nb8);
	ft_printf(">>>|%+05hhd$\n", nb8);
	printf("\n");
	printf("===|%0+5hhd$\n", nb8);
	ft_printf(">>>|%0+5hhd$\n", nb8);
	printf("\n");
	printf("===|%05.3hhd$\n", nb8);
	ft_printf(">>>|%05.3hhd$\n", nb8);
	printf("\n");
	printf("===|%-5.3hhd$\n", nb8);
	ft_printf(">>>|%-5.3hhd$\n", nb8);
	printf("\n");
	printf("===|%+05.3hhd$\n", nb8);
	ft_printf(">>>|%+05.3hhd$\n", nb8);
	printf("\n");
	printf("===|%0 5.3hhd$\n", nb8);
	ft_printf(">>>|%0 5.3hhd$\n", nb8);
	printf("\n");
	printf("===|% 05.3hhd$\n", nb8);
	ft_printf(">>>|% 05.3hhd$\n", nb8);
	printf("\n");
	printf("===|%-+5.3hhd$\n", nb8);
	ft_printf(">>>|%-+5.3hhd$\n", nb8);
	printf("\n");

	short nb9 = -23;
	printf("===|% hd$\n", nb9);
	ft_printf(">>>|% hd$\n", nb9);
	printf("\n");
	printf("===|%+hd$\n", nb9);
	ft_printf(">>>|%+hd$\n", nb9);
	printf("\n");
	printf("===|%.5hd$\n", nb9);
	ft_printf(">>>|%.5hd$\n", nb9);
	printf("\n");
	printf("===|% .5hd$\n", nb9);
	ft_printf(">>>|% .5hd$\n", nb9);
	printf("\n");
	printf("===|%+.5hd$\n", nb9);
	ft_printf(">>>|%+.5hd$\n", nb9);
	printf("\n");
	printf("===|%0.5hd$\n", nb9);
	ft_printf(">>>|%0.5hd$\n", nb9);
	printf("\n");
	printf("===|%-.5hd$\n", nb9);
	ft_printf(">>>|%-.5hd$\n", nb9);
	printf("\n");
	printf("===|%5hd$\n", nb9);
	ft_printf(">>>|%5hd$\n", nb9);
	printf("\n");
	printf("===|% 5hd$\n", nb9);
	ft_printf(">>>|% 5hd$\n", nb9);
	printf("\n");
	printf("===|%+5hd$\n", nb9);
	ft_printf(">>>|%+5hd$\n", nb9);
	printf("\n");
	printf("===|%-5hd$\n", nb9);
	ft_printf(">>>|%-5hd$\n", nb9);
	printf("\n");
	printf("===|%05hd$\n", nb9);
	ft_printf(">>>|%05hd$\n", nb9);
	printf("\n");
	printf("===|%+05hd$\n", nb9);
	ft_printf(">>>|%+05hd$\n", nb9);
	printf("\n");
	printf("===|%0+5hd$\n", nb9);
	ft_printf(">>>|%0+5hd$\n", nb9);
	printf("\n");
	printf("===|%05.3hd$\n", nb9);
	ft_printf(">>>|%05.3hd$\n", nb9);
	printf("\n");
	printf("===|%-5.3hd$\n", nb9);
	ft_printf(">>>|%-5.3hd$\n", nb9);
	printf("\n");
	printf("===|%+05.3hd$\n", nb9);
	ft_printf(">>>|%+05.3hd$\n", nb9);
	printf("\n");
	printf("===|%0 5.3hd$\n", nb9);
	ft_printf(">>>|%0 5.3hd$\n", nb9);
	printf("\n");
	printf("===|% 05.3hd$\n", nb9);
	ft_printf(">>>|% 05.3hd$\n", nb9);
	printf("\n");
	printf("===|%-+5.3hd$\n", nb9);
	ft_printf(">>>|%-+5.3hd$\n", nb9);
	printf("\n");

	printf("===|%d$\n", INT16_MAX);
	ft_printf(">>>|%d$\n", INT16_MAX);
	printf("\n");
	printf("===|%d$\n", INT16_MIN);
	ft_printf(">>>|%d$\n", INT16_MIN);
	printf("\n");
	printf("===|%d$\n", INT32_MAX);
	ft_printf(">>>|%d$\n", INT32_MAX);
	printf("\n");
	printf("===|%d$\n", INT32_MIN);
	ft_printf(">>>|%d$\n", INT32_MIN);
	printf("\n");
	printf("===|%ld$\n", LONG_MAX);
	ft_printf(">>>|%ld$\n", LONG_MAX);
	printf("\n");
	printf("===|%ld$\n", LONG_MIN);
	ft_printf(">>>|%ld$\n", LONG_MIN);
	printf("\n");
	printf("===|%lld$\n", __LONG_LONG_MAX__);
	ft_printf(">>>|%lld$\n", __LONG_LONG_MAX__);
	printf("\n");
	printf("===|%lld$\n", LLONG_MIN);
	ft_printf(">>>|%lld$\n", LLONG_MIN);
	printf("\n");

	while (1);
	return (0);
}
