/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   test_octal.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: bboucher <bboucher@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/02/01 15:36:04 by bclaudio          #+#    #+#             */
/*   Updated: 2019/02/01 16:18:35 by bboucher         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_printf.h"

void test_octal()
{
	int nb = 0;
	unsigned long nb1 = 12356549864789;
	printf("\ntest o:%o|\n", nb);
	ft_printf("test o:%o\n", nb);
	printf("\nhash:%#o|\n", nb);
	ft_printf("hash:%#o|\n", nb);
	printf("\nprecision / grande:%.5o|\n", nb);
	ft_printf("precision / grande:%.5o|\n", nb);
	printf("\nPrec + hash / grande:%#.5o|\n", nb);
	ft_printf("Prec + hash / grande:%#.5o|\n", nb);
	printf("\nPrec + hash / petite:%#.1o|\n", nb);
	ft_printf("Prec + hash / petite:%#.1o|\n", nb);
	printf("\nPrec + 0:%0.5o|\n", nb);
	ft_printf("Prec + 0:%0.5o|\n", nb);
	printf("\nPrec + minus:%-.5o|\n", nb);
	ft_printf("Prec + minus:%-.5o|\n", nb);
	printf("\nSize:%5o|\n", nb);
	ft_printf("Size:%5o|\n", nb);
	printf("\nsize + prec:%7.3o|\n", nb);
	ft_printf("size + prec:%7.3o|\n", nb);
	printf("\nsize + minus:%-5o|\n", nb);
	ft_printf("size + minus:%-5o|\n", nb);
	printf("\nsize + zero:%05o|\n", nb);
	ft_printf("size + zero:%05o|\n", nb);
	printf("\nsize + zero + hash:%#05o|\n", nb);
	ft_printf("size + zero + hash:%#05o|\n", nb);
	printf("\nsize + zero + prec:%05.3o|\n", nb);
	ft_printf("size + zero + prec:%05.3o\n", nb);
	printf("\nsize + minus + prec:%-5.3o|\n", nb);
	ft_printf("size + minus + prec:%-5.3o|\n", nb);
	printf("\nsize + hash + zero + prec:%#05.3o|\n", nb);
	ft_printf("size + hash + zero + prec:%#05.3o|\n", nb);
	printf("\nsize + hash + zero + prec:%0#5.3o|\n", nb);
	ft_printf("size + hash + zero + prec:%0#5.3o|\n", nb);
	printf("\nsize + hash + minus + prec:%-#7.3o|\n", nb);
	ft_printf("size + hash + minus + prec:%-#7.3o|\n", nb);
	nb = 45;
	printf("\ntest o:%o|\n", nb);
	ft_printf("test o:%o|\n", nb);
	printf("\nhash:%#o|\n", nb);
	ft_printf("hash:%#o|\n", nb);
	printf("\nprecision / grande:%.5o|\n", nb);
	ft_printf("precision / grande:%.5o|\n", nb);
	printf("\nprecision / petite:%.0o|\n", nb);
	ft_printf("precision / petite:%.0o|\n", nb);
	printf("\nPrec + hash / grande:%#.5o|\n", nb);
	ft_printf("Prec + hash / grande:%#.5o|\n", nb);
	printf("\nPrec + hash / petite:%#.1o|\n", nb);
	ft_printf("Prec + hash / petite:%#.1o|\n", nb);
	printf("\nPrec + 0:%0.5o|\n", nb);
	ft_printf("Prec + 0:%0.5o|\n", nb);
	printf("\nPrec + minus:%-.5o|\n", nb);
	ft_printf("Prec + minus:%-.5o|\n", nb);
	printf("\nSize:%5o|\n", nb);
	ft_printf("Size:%5o|\n", nb);
	printf("\nsize + prec:%7.3o|\n", nb);
	ft_printf("size + prec:%7.3o|\n", nb);
	printf("\nsize + minus:%-5o|\n", nb);
	ft_printf("size + minus:%-5o|\n", nb);
	printf("\nsize + zero:%05o|\n", nb);
	ft_printf("size + zero:%05o|\n", nb);
	printf("\nsize + zero + hash:%#05o|\n", nb);
	ft_printf("size + zero + hash:%#05o|\n", nb);
	printf("\nsize + zero + prec:%05.3o|\n", nb);
	ft_printf("size + zero + prec:%05.3o|\n", nb);
	printf("\nsize + minus + prec:%-5.3o|\n", nb);
	ft_printf("size + minus + prec:%-5.3o|\n", nb);
	printf("\nsize + hash + zero + prec:%#05.3o|\n", nb);
	ft_printf("size + hash + zero + prec:%#05.3o|\n", nb);
	printf("\nsize + hash + zero + prec:%0#5.3o|\n", nb);
	ft_printf("size + hash + zero + prec:%0#5.3o|\n", nb);
	printf("\nsize + hash + minus + prec:%-#7.3o|\n", nb);
	ft_printf("size + hash + minus + prec:%-#7.3o|\n", nb);
	nb = 123564789;
	printf("\ntest o:%o|\n", nb);
	ft_printf("test o:%o|\n", nb);
	printf("\nhash:%#o|\n", nb);
	ft_printf("hash:%#o|\n", nb);
	printf("\nprecision / grande:%.5o|\n", nb);
	ft_printf("precision / grande:%.5o|\n", nb);
	printf("\nprecision / petite:%.0o|\n", nb);
	ft_printf("precision / petite:%.0o|\n", nb);
	printf("\nPrec + hash / grande:%#.5o|\n", nb);
	ft_printf("Prec + hash / grande:%#.5o|\n", nb);
	printf("\nPrec + hash / petite:%#.1o|\n", nb);
	ft_printf("Prec + hash / petite:%#.1o|\n", nb);
	printf("\nPrec + 0:%0.5o|\n", nb);
	ft_printf("Prec + 0:%0.5o|\n", nb);
	printf("\nPrec + minus:%-.5o|\n", nb);
	ft_printf("Prec + minus:%-.5o|\n", nb);
	printf("\nSize:%5o|\n", nb);
	ft_printf("Size:%5o|\n", nb);
	printf("\nsize + prec:%7.3o|\n", nb);
	ft_printf("size + prec:%7.3o|\n", nb);
	printf("\nsize + minus:%-5o|\n", nb);
	ft_printf("size + minus:%-5o|\n", nb);
	printf("\nsize + zero:%05o|\n", nb);
	ft_printf("size + zero:%05o|\n", nb);
	printf("\nsize + zero + hash:%#05o|\n", nb);
	ft_printf("size + zero + hash:%#05o|\n", nb);
	printf("\nsize + zero + prec:%05.3o|\n", nb);
	ft_printf("size + zero + prec:%05.3o|\n", nb);
	printf("\nsize + minus + prec:%-5.3o|\n", nb);
	ft_printf("size + minus + prec:%-5.3o|\n", nb);
	printf("\nsize + hash + zero + prec:%#05.3o|\n", nb);
	ft_printf("size + hash + zero + prec:%#05.3o|\n", nb);
	printf("\nsize + hash + zero + prec:%0#5.3o|\n", nb);
	ft_printf("size + hash + zero + prec:%0#5.3o|\n", nb);
	printf("\nsize + hash + minus + prec:%-#7.3o|\n", nb);
	ft_printf("size + hash + minus + prec:%-#7.3o|\n", nb);
	nb = -1235;
	printf("\ntest o:%o|\n", nb);
	ft_printf("test o:%o|\n", nb);
	printf("\nhash:%#o|\n", nb);
	ft_printf("hash:%#o|\n", nb);
	printf("\nprecision / grande:%.5o|\n", nb);
	ft_printf("precision / grande:%.5o|\n", nb);
	printf("\nprecision / petite:%.0o|\n", nb);
	ft_printf("precision / petite:%.0o|\n", nb);
	printf("\nPrec + hash / grande:%#.5o|\n", nb);
	ft_printf("Prec + hash / grande:%#.5o|\n", nb);
	printf("\nPrec + hash / petite:%#.1o|\n", nb);
	ft_printf("Prec + hash / petite:%#.1o|\n", nb);
	printf("\nPrec + 0:%0.5o|\n", nb);
	ft_printf("Prec + 0:%0.5o|\n", nb);
	printf("\nPrec + minus:%-.5o|\n", nb);
	ft_printf("Prec + minus:%-.5o|\n", nb);
	printf("\nSize:%5o|\n", nb);
	ft_printf("Size:%5o|\n", nb);
	printf("\nsize + prec:%7.3o|\n", nb);
	ft_printf("size + prec:%7.3o|\n", nb);
	printf("\nsize + minus:%-5o|\n", nb);
	ft_printf("size + minus:%-5o|\n", nb);
	printf("\nsize + zero:%05o|\n", nb);
	ft_printf("size + zero:%05o|\n", nb);
	printf("\nsize + zero + hash:%#05o|\n", nb);
	ft_printf("size + zero + hash:%#05o|\n", nb);
	printf("\nsize + zero + prec:%05.3o|\n", nb);
	ft_printf("size + zero + prec:%05.3o|\n", nb);
	printf("\nsize + minus + prec:%-5.3o|\n", nb);
	ft_printf("size + minus + prec:%-5.3o|\n", nb);
	printf("\nsize + hash + zero + prec:%#05.3o|\n", nb);
	ft_printf("size + hash + zero + prec:%#05.3o|\n", nb);
	printf("\nsize + hash + zero + prec:%0#5.3o|\n", nb);
	ft_printf("size + hash + zero + prec:%0#5.3o|\n", nb);
	printf("\nsize + hash + minus + prec:%-#7.3o|\n", nb);
	ft_printf("size + hash + minus + prec:%-#7.3o|\n", nb);
	printf("\ntest o:%lo|\n", nb1);
	ft_printf("test o:%lo|\n", nb1);
	printf("\nhash:%#lo|\n", nb1);
	ft_printf("hash:%#lo|\n", nb1);
	printf("\nprecision / grande:%.5lo|\n", nb1);
	ft_printf("precision / grande:%.5lo|\n", nb1);
	printf("\nprecision / petite:%.0lo|\n", nb1);
	ft_printf("precision / petite:%.0lo|\n", nb1);
	printf("\nPrec + hash / grande:%#.5lo|\n", nb1);
	ft_printf("Prec + hash / grande:%#.5lo|\n", nb1);
	printf("\nPrec + hash / petite:%#.1lo|\n", nb1);
	ft_printf("Prec + hash / petite:%#.1lo|\n", nb1);
	printf("\nPrec + 0:%0.5lo|\n", nb1);
	ft_printf("Prec + 0:%0.5lo|\n", nb1);
	printf("\nPrec + minus:%-.5lo|\n", nb1);
	ft_printf("Prec + minus:%-.5lo|\n", nb1);
	printf("\nSize:%5lo|\n", nb1);
	ft_printf("Size:%5lo|\n", nb1);
	printf("\nsize + prec:%7.3lo|\n", nb1);
	ft_printf("size + prec:%7.3lo|\n", nb1);
	printf("\nsize + minus:%-5lo|\n", nb1);
	ft_printf("size + minus:%-5lo|\n", nb1);
	printf("\nsize + zero:%05lo|\n", nb1);
	ft_printf("size + zero:%05lo|\n", nb1);
	printf("\nsize + zero + hash:%#05lo|\n", nb1);
	ft_printf("size + zero + hash:%#05lo|\n", nb1);
	printf("\nsize + zero + prec:%05.3lo|\n", nb1);
	ft_printf("size + zero + prec:%05.3lo|\n", nb1);
	printf("\nsize + minus + prec:%-5.3lo|\n", nb1);
	ft_printf("size + minus + prec:%-5.3lo|\n", nb1);
	printf("\nsize + hash + zero + prec:%#05.3lo|\n", nb1);
	ft_printf("size + hash + zero + prec:%#05.3lo|\n", nb1);
	printf("\nsize + hash + zero + prec:%0#5.3lo|\n", nb1);
	ft_printf("size + hash + zero + prec:%0#5.3lo|\n", nb1);
	printf("\nsize + hash + minus + prec:%-#7.3lo|\n", nb1);
	ft_printf("size + hash + minus + prec:%-#7.3lo|\n", nb1);
}
